spring:
  application:
    name: ecommerce-enterprise-senior-v2
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${SPRING_DATASOURCE_USERNAME:ecommerce}
    password: ${SPRING_DATASOURCE_PASSWORD:ecommerce}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:ecommerce}
    password: ${SPRING_RABBITMQ_PASSWORD:ecommerce}
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
app:
  jwt:
    secret: ${APP_JWT_SECRET:portfolio-enterprise-secret-key-change-me-please-32chars}
    issuer: ecommerce-portfolio
    expiration-minutes: 120
  messaging:
    exchange: ecommerce.events
    order-created-routing-key: order.created
    payment-approved-routing-key: payment.approved
    payment-rejected-routing-key: payment.rejected

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] [%thread] %logger{36} - %msg%n"